package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMPANY_INFO.
 */
public class CompanyInfo {

    private Long id;
    private String com_id;
    private String emid;
    private String com_fullname;
    private String com_name;
    private String org_id;
    private String org_idstr;
    private Boolean is_choose;

    public CompanyInfo() {
    }

    public CompanyInfo(Long id) {
        this.id = id;
    }

    public CompanyInfo(Long id, String com_id, String emid, String com_fullname, String com_name, String org_id, String org_idstr, Boolean is_choose) {
        this.id = id;
        this.com_id = com_id;
        this.emid = emid;
        this.com_fullname = com_fullname;
        this.com_name = com_name;
        this.org_id = org_id;
        this.org_idstr = org_idstr;
        this.is_choose = is_choose;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCom_id() {
        return com_id;
    }

    public void setCom_id(String com_id) {
        this.com_id = com_id;
    }

    public String getEmid() {
        return emid;
    }

    public void setEmid(String emid) {
        this.emid = emid;
    }

    public String getCom_fullname() {
        return com_fullname;
    }

    public void setCom_fullname(String com_fullname) {
        this.com_fullname = com_fullname;
    }

    public String getCom_name() {
        return com_name;
    }

    public void setCom_name(String com_name) {
        this.com_name = com_name;
    }

    public String getOrg_id() {
        return org_id;
    }

    public void setOrg_id(String org_id) {
        this.org_id = org_id;
    }

    public String getOrg_idstr() {
        return org_idstr;
    }

    public void setOrg_idstr(String org_idstr) {
        this.org_idstr = org_idstr;
    }

    public Boolean getIs_choose() {
        return is_choose;
    }

    public void setIs_choose(Boolean is_choose) {
        this.is_choose = is_choose;
    }

}
