package com.cqj.test.wbd2_gwpy;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cqj.test.wbd2_gwpy.UserInfo;
import com.cqj.test.wbd2_gwpy.CompanyInfo;
import com.cqj.test.wbd2_gwpy.RwInfo;
import com.cqj.test.wbd2_gwpy.CsInfo;
import com.cqj.test.wbd2_gwpy.SbInfo;
import com.cqj.test.wbd2_gwpy.JcbInfo;
import com.cqj.test.wbd2_gwpy.JcbDetailInfo;
import com.cqj.test.wbd2_gwpy.AqjcCommitInfo;
import com.cqj.test.wbd2_gwpy.SbjcCommitInfo;
import com.cqj.test.wbd2_gwpy.SbjcListInfo;
import com.cqj.test.wbd2_gwpy.YhfcInfo;
import com.cqj.test.wbd2_gwpy.YhfcCommitInfo;
import com.cqj.test.wbd2_gwpy.YhzgCommitInfo;

import com.cqj.test.wbd2_gwpy.UserInfoDao;
import com.cqj.test.wbd2_gwpy.CompanyInfoDao;
import com.cqj.test.wbd2_gwpy.RwInfoDao;
import com.cqj.test.wbd2_gwpy.CsInfoDao;
import com.cqj.test.wbd2_gwpy.SbInfoDao;
import com.cqj.test.wbd2_gwpy.JcbInfoDao;
import com.cqj.test.wbd2_gwpy.JcbDetailInfoDao;
import com.cqj.test.wbd2_gwpy.AqjcCommitInfoDao;
import com.cqj.test.wbd2_gwpy.SbjcCommitInfoDao;
import com.cqj.test.wbd2_gwpy.SbjcListInfoDao;
import com.cqj.test.wbd2_gwpy.YhfcInfoDao;
import com.cqj.test.wbd2_gwpy.YhfcCommitInfoDao;
import com.cqj.test.wbd2_gwpy.YhzgCommitInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig companyInfoDaoConfig;
    private final DaoConfig rwInfoDaoConfig;
    private final DaoConfig csInfoDaoConfig;
    private final DaoConfig sbInfoDaoConfig;
    private final DaoConfig jcbInfoDaoConfig;
    private final DaoConfig jcbDetailInfoDaoConfig;
    private final DaoConfig aqjcCommitInfoDaoConfig;
    private final DaoConfig sbjcCommitInfoDaoConfig;
    private final DaoConfig sbjcListInfoDaoConfig;
    private final DaoConfig yhfcInfoDaoConfig;
    private final DaoConfig yhfcCommitInfoDaoConfig;
    private final DaoConfig yhzgCommitInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final CompanyInfoDao companyInfoDao;
    private final RwInfoDao rwInfoDao;
    private final CsInfoDao csInfoDao;
    private final SbInfoDao sbInfoDao;
    private final JcbInfoDao jcbInfoDao;
    private final JcbDetailInfoDao jcbDetailInfoDao;
    private final AqjcCommitInfoDao aqjcCommitInfoDao;
    private final SbjcCommitInfoDao sbjcCommitInfoDao;
    private final SbjcListInfoDao sbjcListInfoDao;
    private final YhfcInfoDao yhfcInfoDao;
    private final YhfcCommitInfoDao yhfcCommitInfoDao;
    private final YhzgCommitInfoDao yhzgCommitInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        companyInfoDaoConfig = daoConfigMap.get(CompanyInfoDao.class).clone();
        companyInfoDaoConfig.initIdentityScope(type);

        rwInfoDaoConfig = daoConfigMap.get(RwInfoDao.class).clone();
        rwInfoDaoConfig.initIdentityScope(type);

        csInfoDaoConfig = daoConfigMap.get(CsInfoDao.class).clone();
        csInfoDaoConfig.initIdentityScope(type);

        sbInfoDaoConfig = daoConfigMap.get(SbInfoDao.class).clone();
        sbInfoDaoConfig.initIdentityScope(type);

        jcbInfoDaoConfig = daoConfigMap.get(JcbInfoDao.class).clone();
        jcbInfoDaoConfig.initIdentityScope(type);

        jcbDetailInfoDaoConfig = daoConfigMap.get(JcbDetailInfoDao.class).clone();
        jcbDetailInfoDaoConfig.initIdentityScope(type);

        aqjcCommitInfoDaoConfig = daoConfigMap.get(AqjcCommitInfoDao.class).clone();
        aqjcCommitInfoDaoConfig.initIdentityScope(type);

        sbjcCommitInfoDaoConfig = daoConfigMap.get(SbjcCommitInfoDao.class).clone();
        sbjcCommitInfoDaoConfig.initIdentityScope(type);

        sbjcListInfoDaoConfig = daoConfigMap.get(SbjcListInfoDao.class).clone();
        sbjcListInfoDaoConfig.initIdentityScope(type);

        yhfcInfoDaoConfig = daoConfigMap.get(YhfcInfoDao.class).clone();
        yhfcInfoDaoConfig.initIdentityScope(type);

        yhfcCommitInfoDaoConfig = daoConfigMap.get(YhfcCommitInfoDao.class).clone();
        yhfcCommitInfoDaoConfig.initIdentityScope(type);

        yhzgCommitInfoDaoConfig = daoConfigMap.get(YhzgCommitInfoDao.class).clone();
        yhzgCommitInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        companyInfoDao = new CompanyInfoDao(companyInfoDaoConfig, this);
        rwInfoDao = new RwInfoDao(rwInfoDaoConfig, this);
        csInfoDao = new CsInfoDao(csInfoDaoConfig, this);
        sbInfoDao = new SbInfoDao(sbInfoDaoConfig, this);
        jcbInfoDao = new JcbInfoDao(jcbInfoDaoConfig, this);
        jcbDetailInfoDao = new JcbDetailInfoDao(jcbDetailInfoDaoConfig, this);
        aqjcCommitInfoDao = new AqjcCommitInfoDao(aqjcCommitInfoDaoConfig, this);
        sbjcCommitInfoDao = new SbjcCommitInfoDao(sbjcCommitInfoDaoConfig, this);
        sbjcListInfoDao = new SbjcListInfoDao(sbjcListInfoDaoConfig, this);
        yhfcInfoDao = new YhfcInfoDao(yhfcInfoDaoConfig, this);
        yhfcCommitInfoDao = new YhfcCommitInfoDao(yhfcCommitInfoDaoConfig, this);
        yhzgCommitInfoDao = new YhzgCommitInfoDao(yhzgCommitInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(CompanyInfo.class, companyInfoDao);
        registerDao(RwInfo.class, rwInfoDao);
        registerDao(CsInfo.class, csInfoDao);
        registerDao(SbInfo.class, sbInfoDao);
        registerDao(JcbInfo.class, jcbInfoDao);
        registerDao(JcbDetailInfo.class, jcbDetailInfoDao);
        registerDao(AqjcCommitInfo.class, aqjcCommitInfoDao);
        registerDao(SbjcCommitInfo.class, sbjcCommitInfoDao);
        registerDao(SbjcListInfo.class, sbjcListInfoDao);
        registerDao(YhfcInfo.class, yhfcInfoDao);
        registerDao(YhfcCommitInfo.class, yhfcCommitInfoDao);
        registerDao(YhzgCommitInfo.class, yhzgCommitInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        companyInfoDaoConfig.getIdentityScope().clear();
        rwInfoDaoConfig.getIdentityScope().clear();
        csInfoDaoConfig.getIdentityScope().clear();
        sbInfoDaoConfig.getIdentityScope().clear();
        jcbInfoDaoConfig.getIdentityScope().clear();
        jcbDetailInfoDaoConfig.getIdentityScope().clear();
        aqjcCommitInfoDaoConfig.getIdentityScope().clear();
        sbjcCommitInfoDaoConfig.getIdentityScope().clear();
        sbjcListInfoDaoConfig.getIdentityScope().clear();
        yhfcInfoDaoConfig.getIdentityScope().clear();
        yhfcCommitInfoDaoConfig.getIdentityScope().clear();
        yhzgCommitInfoDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public CompanyInfoDao getCompanyInfoDao() {
        return companyInfoDao;
    }

    public RwInfoDao getRwInfoDao() {
        return rwInfoDao;
    }

    public CsInfoDao getCsInfoDao() {
        return csInfoDao;
    }

    public SbInfoDao getSbInfoDao() {
        return sbInfoDao;
    }

    public JcbInfoDao getJcbInfoDao() {
        return jcbInfoDao;
    }

    public JcbDetailInfoDao getJcbDetailInfoDao() {
        return jcbDetailInfoDao;
    }

    public AqjcCommitInfoDao getAqjcCommitInfoDao() {
        return aqjcCommitInfoDao;
    }

    public SbjcCommitInfoDao getSbjcCommitInfoDao() {
        return sbjcCommitInfoDao;
    }

    public SbjcListInfoDao getSbjcListInfoDao() {
        return sbjcListInfoDao;
    }

    public YhfcInfoDao getYhfcInfoDao() {
        return yhfcInfoDao;
    }

    public YhfcCommitInfoDao getYhfcCommitInfoDao() {
        return yhfcCommitInfoDao;
    }

    public YhzgCommitInfoDao getYhzgCommitInfoDao() {
        return yhzgCommitInfoDao;
    }

}
