package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.cqj.test.wbd2_gwpy.myinterface.IChooseItem;

/**
 * Entity mapped to table JCB_INFO.
 */
public class JcbInfo implements IChooseItem{

    private Long id;
    private String jcbid;
    private String jcbname;
    private Boolean is_choose;

    public JcbInfo() {
    }

    public JcbInfo(Long id) {
        this.id = id;
    }

    public JcbInfo(Long id, String jcbid, String jcbname, Boolean is_choose) {
        this.id = id;
        this.jcbid = jcbid;
        this.jcbname = jcbname;
        this.is_choose = is_choose;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJcbid() {
        return jcbid;
    }

    public void setJcbid(String jcbid) {
        this.jcbid = jcbid;
    }

    public String getJcbname() {
        return jcbname;
    }

    public void setJcbname(String jcbname) {
        this.jcbname = jcbname;
    }

    public Boolean getIs_choose() {
        return is_choose;
    }

    public void setIs_choose(Boolean is_choose) {
        this.is_choose = is_choose;
    }

    @Override
    public String getItemName() {
        return jcbname;
    }

    @Override
    public String getItemId() {
        return jcbid;
    }

    @Override
    public String getCsId() {
        return null;
    }
}
