package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGIN_INFO.
 */
public class LoginInfo {

    private Long id;
    /** Not-null value. */
    private String login_name;
    private String login_pwd;
    private Boolean is_login;
    private java.util.Date date;

    public LoginInfo() {
    }

    public LoginInfo(Long id) {
        this.id = id;
    }

    public LoginInfo(Long id, String login_name, String login_pwd, Boolean is_login, java.util.Date date) {
        this.id = id;
        this.login_name = login_name;
        this.login_pwd = login_pwd;
        this.is_login = is_login;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLogin_name() {
        return login_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin_name(String login_name) {
        this.login_name = login_name;
    }

    public String getLogin_pwd() {
        return login_pwd;
    }

    public void setLogin_pwd(String login_pwd) {
        this.login_pwd = login_pwd;
    }

    public Boolean getIs_login() {
        return is_login;
    }

    public void setIs_login(Boolean is_login) {
        this.is_login = is_login;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
