package com.cqj.test.wbd2_gwpy;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cqj.test.wbd2_gwpy.RwInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RW_INFO.
*/
public class RwInfoDao extends AbstractDao<RwInfo, Long> {

    public static final String TABLENAME = "RW_INFO";

    /**
     * Properties of entity RwInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Partid = new Property(1, String.class, "partid", false, "PARTID");
        public final static Property Partname = new Property(2, String.class, "partname", false, "PARTNAME");
        public final static Property Is_choose = new Property(3, Boolean.class, "is_choose", false, "IS_CHOOSE");
    };


    public RwInfoDao(DaoConfig config) {
        super(config);
    }
    
    public RwInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RW_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PARTID' TEXT," + // 1: partid
                "'PARTNAME' TEXT," + // 2: partname
                "'IS_CHOOSE' INTEGER);"); // 3: is_choose
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RW_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RwInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String partid = entity.getPartid();
        if (partid != null) {
            stmt.bindString(2, partid);
        }
 
        String partname = entity.getPartname();
        if (partname != null) {
            stmt.bindString(3, partname);
        }
 
        Boolean is_choose = entity.getIs_choose();
        if (is_choose != null) {
            stmt.bindLong(4, is_choose ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RwInfo readEntity(Cursor cursor, int offset) {
        RwInfo entity = new RwInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // partid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // partname
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // is_choose
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RwInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPartid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPartname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIs_choose(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RwInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RwInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
