package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.cqj.test.wbd2_gwpy.myinterface.IChooseItem;

/**
 * Entity mapped to table SB_INFO.
 */
public class SbInfo implements IChooseItem{

    private Long id;
    private String sbid;
    private String sbname;
    private String csid;
    private Boolean is_choose;

    public SbInfo() {
    }

    public SbInfo(Long id) {
        this.id = id;
    }

    public SbInfo(Long id, String sbid, String sbname, String csid, Boolean is_choose) {
        this.id = id;
        this.sbid = sbid;
        this.sbname = sbname;
        this.csid = csid;
        this.is_choose = is_choose;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSbid() {
        return sbid;
    }

    public void setSbid(String sbid) {
        this.sbid = sbid;
    }

    public String getSbname() {
        return sbname;
    }

    public void setSbname(String sbname) {
        this.sbname = sbname;
    }

    public String getCsid() {
        return csid;
    }

    public void setCsid(String csid) {
        this.csid = csid;
    }

    public Boolean getIs_choose() {
        return is_choose;
    }

    public void setIs_choose(Boolean is_choose) {
        this.is_choose = is_choose;
    }

    @Override
    public String getItemName() {
        return sbname;
    }

    @Override
    public String getItemId() {
        return sbid;
    }

    @Override
    public String getCsId() {
        return csid;
    }
}
