package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.content.Context;

import com.cqj.test.wbd2_gwpy.dao.SqliteOperator;
import com.cqj.test.wbd2_gwpy.myinterface.INoCommitItem;
import com.cqj.test.wbd2_gwpy.util.WebServiceUtil;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

/**
 * Entity mapped to table SBJC_COMMIT_INFO.
 */
public class SbjcCommitInfo implements INoCommitItem {

    private Long id;
    private Integer CPID;
    private String cpName;
    private String cDate;
    private Integer cEmid;
    private Integer rEmid;
    private String cRemark;
    private String cState;
    private Date checkDate;
    private boolean isSuccess;

    public SbjcCommitInfo() {
    }

    public SbjcCommitInfo(Long id) {
        this.id = id;
    }

    public SbjcCommitInfo(Long id, Integer CPID, String cpName, String cDate, Integer cEmid, Integer rEmid, String cRemark, String cState, Date checkDate) {
        this.id = id;
        this.CPID = CPID;
        this.cpName = cpName;
        this.cDate = cDate;
        this.cEmid = cEmid;
        this.rEmid = rEmid;
        this.cRemark = cRemark;
        this.cState = cState;
        this.checkDate = checkDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCPID() {
        return CPID;
    }

    public void setCPID(Integer CPID) {
        this.CPID = CPID;
    }

    public String getCpName() {
        return cpName;
    }

    public void setCpName(String cpName) {
        this.cpName = cpName;
    }

    public String getCDate() {
        return cDate;
    }

    public void setCDate(String cDate) {
        this.cDate = cDate;
    }

    public Integer getCEmid() {
        return cEmid;
    }

    public void setCEmid(Integer cEmid) {
        this.cEmid = cEmid;
    }

    public Integer getREmid() {
        return rEmid;
    }

    public void setREmid(Integer rEmid) {
        this.rEmid = rEmid;
    }

    public String getCRemark() {
        return cRemark;
    }

    public void setCRemark(String cRemark) {
        this.cRemark = cRemark;
    }

    public String getCState() {
        return cState;
    }

    public void setCState(String cState) {
        this.cState = cState;
    }

    public Date getCheckDate() {
        return checkDate;
    }

    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    @Override
    public String getName() {
        return cpName;
    }

    @Override
    public String getDetail() {
        return cRemark;
    }

    @Override
    public String getDate() {
        return android.text.format.DateFormat.format("yyyy年MM月dd日", new Date()).toString();
    }

    @Override
    public boolean isCommitSuccess() {
        return isSuccess;
    }

    @Override
    public void setCommitSuccess(boolean pIsSuccess) {
        this.isSuccess = pIsSuccess;
    }

    @Override
    public ArrayList<HashMap<String, Object>> upload() throws Exception {
        String[] keys = {"CPID", "cDate", "cEmid", "rEmid",
                "cRemark", "cState"};
        Object[] values = {getCPID(), getCDate(), getCEmid(), getREmid(),
                getCRemark(),
                getCState()};
        return WebServiceUtil.getWebServiceMsg(keys,
                values, "AddSafetySetCheck", new String[]{"retstr"},
                WebServiceUtil.SAFE_URL);
    }

    @Override
    public void deleteCommit(Context context) {
        SbjcCommitInfoDao aqjcDao = SqliteOperator.INSTANCE.getSbCommitDao(context);
        aqjcDao.delete(this);
    }
}
