package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

    private Long id;
    private int uid;
    /** Not-null value. */
    private String login_name;
    private String login_pwd;
    private String name;
    private String nick_name;
    private String phone_number;
    private String xuliehao;
    private String tongdao;
    private Boolean is_login;
    private java.util.Date date;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, int uid, String login_name, String login_pwd, String name, String nick_name, String phone_number, String xuliehao, String tongdao, Boolean is_login, java.util.Date date) {
        this.id = id;
        this.uid = uid;
        this.login_name = login_name;
        this.login_pwd = login_pwd;
        this.name = name;
        this.nick_name = nick_name;
        this.phone_number = phone_number;
        this.xuliehao = xuliehao;
        this.tongdao = tongdao;
        this.is_login = is_login;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    /** Not-null value. */
    public String getLogin_name() {
        return login_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin_name(String login_name) {
        this.login_name = login_name;
    }

    public String getLogin_pwd() {
        return login_pwd;
    }

    public void setLogin_pwd(String login_pwd) {
        this.login_pwd = login_pwd;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getXuliehao() {
        return xuliehao;
    }

    public void setXuliehao(String xuliehao) {
        this.xuliehao = xuliehao;
    }

    public String getTongdao() {
        return tongdao;
    }

    public void setTongdao(String tongdao) {
        this.tongdao = tongdao;
    }

    public Boolean getIs_login() {
        return is_login;
    }

    public void setIs_login(Boolean is_login) {
        this.is_login = is_login;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
