package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.content.Context;

import com.cqj.test.wbd2_gwpy.dao.SqliteOperator;
import com.cqj.test.wbd2_gwpy.myinterface.INoCommitItem;
import com.cqj.test.wbd2_gwpy.util.UploadDataHelper;
import com.cqj.test.wbd2_gwpy.util.WebServiceUtil;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Entity mapped to table YHFC_COMMIT_INFO.
 */
public class YhfcCommitInfo implements INoCommitItem{

    private Long id;
    private Integer troubleid;
    private String troubleName;
    private String reviewEmids;
    private String reviewRemark;
    private String reviewDate;
    private String dightedImgPath;
    private boolean isSuccess;

    public YhfcCommitInfo() {
    }

    public YhfcCommitInfo(Long id) {
        this.id = id;
    }

    public YhfcCommitInfo(Long id, Integer troubleid, String troubleName, String reviewEmids, String reviewRemark, String reviewDate, String dightedImgPath) {
        this.id = id;
        this.troubleid = troubleid;
        this.troubleName = troubleName;
        this.reviewEmids = reviewEmids;
        this.reviewRemark = reviewRemark;
        this.reviewDate = reviewDate;
        this.dightedImgPath = dightedImgPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTroubleid() {
        return troubleid;
    }

    public void setTroubleid(Integer troubleid) {
        this.troubleid = troubleid;
    }

    public String getTroubleName() {
        return troubleName;
    }

    public void setTroubleName(String troubleName) {
        this.troubleName = troubleName;
    }

    public String getReviewEmids() {
        return reviewEmids;
    }

    public void setReviewEmids(String reviewEmids) {
        this.reviewEmids = reviewEmids;
    }

    public String getReviewRemark() {
        return reviewRemark;
    }

    public void setReviewRemark(String reviewRemark) {
        this.reviewRemark = reviewRemark;
    }

    public String getReviewDate() {
        return reviewDate;
    }

    public void setReviewDate(String reviewDate) {
        this.reviewDate = reviewDate;
    }

    public String getDightedImgPath() {
        return dightedImgPath;
    }

    public void setDightedImgPath(String dightedImgPath) {
        this.dightedImgPath = dightedImgPath;
    }

    @Override
    public String getName() {
        return troubleName;
    }

    @Override
    public String getDetail() {
        return reviewRemark;
    }

    @Override
    public String getDate() {
        return reviewDate;
    }

    @Override
    public boolean isCommitSuccess() {
        return isSuccess;
    }

    @Override
    public void setCommitSuccess(boolean pIsSuccess) {
        isSuccess =pIsSuccess;
    }

    @Override
    public ArrayList<HashMap<String, Object>> upload() throws Exception {
        return UploadDataHelper.uploadYhfc(this);
    }

    @Override
    public void deleteCommit(Context context) {
        SqliteOperator.INSTANCE.getYhfcCommitInfo(context).delete(this);
    }
}
