package com.cqj.test.wbd2_gwpy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.content.Context;

import com.cqj.test.wbd2_gwpy.dao.SqliteOperator;
import com.cqj.test.wbd2_gwpy.myinterface.INoCommitItem;
import com.cqj.test.wbd2_gwpy.util.UploadDataHelper;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Entity mapped to table YHZG_COMMIT_INFO.
 */
public class YhzgCommitInfo implements INoCommitItem {

    private Long id;
    private Integer troubleid;
    private String troubleName;
    private String finishedDate;
    private String results;
    private String evalstr;
    private String factCost;
    private String Imgpath;
    private boolean isSuccess;

    public YhzgCommitInfo() {
    }

    public YhzgCommitInfo(Long id) {
        this.id = id;
    }

    public YhzgCommitInfo(Long id, Integer troubleid, String troubleName, String finishedDate, String results, String evalstr, String factCost, String Imgpath) {
        this.id = id;
        this.troubleid = troubleid;
        this.troubleName = troubleName;
        this.finishedDate = finishedDate;
        this.results = results;
        this.evalstr = evalstr;
        this.factCost = factCost;
        this.Imgpath = Imgpath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTroubleid() {
        return troubleid;
    }

    public void setTroubleid(Integer troubleid) {
        this.troubleid = troubleid;
    }

    public String getTroubleName() {
        return troubleName;
    }

    public void setTroubleName(String troubleName) {
        this.troubleName = troubleName;
    }

    public String getFinishedDate() {
        return finishedDate;
    }

    public void setFinishedDate(String finishedDate) {
        this.finishedDate = finishedDate;
    }

    public String getResults() {
        return results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    public String getEvalstr() {
        return evalstr;
    }

    public void setEvalstr(String evalstr) {
        this.evalstr = evalstr;
    }

    public String getFactCost() {
        return factCost;
    }

    public void setFactCost(String factCost) {
        this.factCost = factCost;
    }

    public String getImgpath() {
        return Imgpath;
    }

    public void setImgpath(String Imgpath) {
        this.Imgpath = Imgpath;
    }

    @Override
    public String getName() {
        return troubleName;
    }

    @Override
    public String getDetail() {
        return results;
    }

    @Override
    public String getDate() {
        return finishedDate;
    }

    @Override
    public boolean isCommitSuccess() {
        return isSuccess;
    }

    @Override
    public void setCommitSuccess(boolean pIsSuccess) {
        isSuccess = pIsSuccess;
    }

    @Override
    public ArrayList<HashMap<String, Object>> upload() throws Exception {
        return UploadDataHelper.uploadYhzg(this);
    }

    @Override
    public void deleteCommit(Context context) {
        SqliteOperator.INSTANCE.getYhzgCommitInfo(context).delete(this);
    }
}
